set(SUBDIR_NAME Dialogs)

# Include the Utilities sources
include(${IMFViewer_SOURCE_DIR}/${SUBDIR_NAME}/Utilities/SourceList.cmake)

# --------------------------------------------------------------------
# Any Class that inherits from QObject, either directly or through the heirarchy needs to have its header listed here
set(IMFViewer_${SUBDIR_NAME}_Moc_HDRS
  ${IMFViewer_SOURCE_DIR}/${SUBDIR_NAME}/LoadHDF5FileDialog.h
  )
# --------------------------------------------------------------------
# Run Qts automoc program to generate some source files that get compiled
QT5_WRAP_CPP( IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS ${IMFViewer_${SUBDIR_NAME}_Moc_HDRS})
set_source_files_properties( ${IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS} PROPERTIES GENERATED TRUE)
set_source_files_properties( ${IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS} PROPERTIES HEADER_FILE_ONLY TRUE)

set(IMFViewer_${SUBDIR_NAME}_HDRS

)

set(IMFViewer_${SUBDIR_NAME}_SRCS
  ${IMFViewer_SOURCE_DIR}/${SUBDIR_NAME}/LoadHDF5FileDialog.cpp
)

# The UI files As generated by Qt Designer
SET(IMFViewer_${SUBDIR_NAME}_UIS
  ${IMFViewer_SOURCE_DIR}/${SUBDIR_NAME}/UI_Files/LoadHDF5FileDialog.ui
)

cmp_IDE_GENERATED_PROPERTIES("${SUBDIR_NAME}/UI_Files" "${IMFViewer_${SUBDIR_NAME}_UIS}" "")

# this will run uic on .ui files:
QT5_WRAP_UI( IMFViewer_${SUBDIR_NAME}_Generated_UI_HDRS ${IMFViewer_${SUBDIR_NAME}_UIS} )

cmp_IDE_SOURCE_PROPERTIES( "${SUBDIR_NAME}" "${IMFViewer_${SUBDIR_NAME}_HDRS};${IMFViewer_${SUBDIR_NAME}_Moc_HDRS}" "${IMFViewer_${SUBDIR_NAME}_SRCS}" "${PROJECT_INSTALL_HEADERS}")
cmp_IDE_SOURCE_PROPERTIES( "Generated/${SUBDIR_NAME}" "" "${IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS}" "0")

#-- Put the generated files into their own group for IDEs
cmp_IDE_GENERATED_PROPERTIES("Generated/ui" "${IMFViewer_${SUBDIR_NAME}_Generated_UI_HDRS}" "")
cmp_IDE_GENERATED_PROPERTIES("Generated/moc" "${IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS}" "")

set(IMFViewer_${SUBDIR_NAME}_HDRS
  ${IMFViewer_${SUBDIR_NAME}_HDRS}
  ${IMFViewer_${SUBDIR_NAME}_Moc_HDRS}  # Add the headers that get Moc'ed here so they show up in solutions/IDEs/Project files
)

set(IMFViewer_${SUBDIR_NAME}_SRCS
  ${IMFViewer_${SUBDIR_NAME}_SRCS}
  ${IMFViewer_${SUBDIR_NAME}_Generated_MOC_SRCS}
)

